# user_rate

In [1]:
import pandas as pd

In [25]:
df = pd.DataFrame([
        ['android', 'oppo', 'A1', '微信', 60],
        ['android', 'oppo', 'A1', '今日头条', 50],
        ['android', 'oppo', 'A2', '今日头条', 30],
        ['android', 'oppo', 'A2', '微信', 30],
        ['android', 'oppo', 'A3', '今日头条', 20],
        ['android', 'oppo', 'A3', '微信', 50],
        ['android', 'oppo', 'A3', '手机百度', 40],
        ['android', 'oppo', 'A4', '手机百度', 20],
        ['android', 'oppo', 'A5', '微信', 60],
        ['android', 'huawei', 'B1', '手机百度', 55],
        ['android', 'huawei', 'B2', '今日头条', 50],
        ['android', 'huawei', 'B2', '今日头条', 30],
        ['android', 'huawei', 'B2', '微信', 30],
        ['android', 'huawei', 'B3', '今日头条', 20],
        ['android', 'huawei', 'B3', '微信', 50],
        ['android', 'huawei', 'B4', '手机百度', 40],
        ['android', 'huawei', 'B4', '手机百度', 20],
        ['android', 'huawei', 'B5', '微信', 60],
        ['ios', 'iphone', 'C1', '微信', 120],
        ['ios', 'iphone', 'C2', '微信', 100],
        ['ios', 'iphone', 'C2', '手机百度', 50],
        ['ios', 'iphone', 'C3', '微信', 80],
        ['ios', 'iphone', 'C3', '手机百度', 50],
        ['ios', 'iphone', 'C3', '今日头条', 40],
        ['ios', 'iphone', 'C4', '手机百度', 50],
        ['ios', 'iphone', 'C5', '今日头条', 60],
        ['ios', 'iphone', 'C6', '微信', 40],
    ], columns=['os', 'brand', 'uid', 'app', 'usetime'])

In [26]:
df

         os   brand uid   app  usetime
0   android    oppo  A1    微信       60
1   android    oppo  A1  今日头条       50
2   android    oppo  A2  今日头条       30
3   android    oppo  A2    微信       30
4   android    oppo  A3  今日头条       20
5   android    oppo  A3    微信       50
6   android    oppo  A3  手机百度       40
7   android    oppo  A4  手机百度       20
8   android    oppo  A5    微信       60
9   android  huawei  B1  手机百度       55
10  android  huawei  B2  今日头条       50
11  android  huawei  B2  今日头条       30
12  android  huawei  B2    微信       30
13  android  huawei  B3  今日头条       20
14  android  huawei  B3    微信       50
15  android  huawei  B4  手机百度       40
16  android  huawei  B4  手机百度       20
17  android  huawei  B5    微信       60
18      ios  iphone  C1    微信      120
19      ios  iphone  C2    微信      100
20      ios  iphone  C2  手机百度       50
21      ios  iphone  C3    微信       80
22      ios  iphone  C3  手机百度       50
23      ios  iphone  C3  今日头条       40
24      ios  iphone  C4  手机百度       50
25      ios  iphone  C4  今日头条       60
26      ios  iphone  C5    微信       40

In [107]:
def inst_cover(df, mask, cols):
    n = len(cols)
    a = df.groupby(cols[:n-1])[cols[-1]].nunique()
    b = df.groupby(cols[:n-2])[cols[-1]].nunique()
    c = a.to_frame().unstack()/b.values
    c.columns = c.columns.droplevel(0)
    return c#.reset_index()
    
cols = ['os', 'brand', 'app', 'uid']
c=inst_cover(df, mask, cols)

In [114]:
c.reset_index()

app       os   brand  今日头条   微信  手机百度
0    android  huawei   0.4  0.6   0.4
1    android    oppo   0.6  0.8   0.4
2        ios  iphone   0.4  0.8   0.6

In [ ]:
# 多级索引读取
# https://blog.csdn.net/anshuai_aw1/article/details/83510345
idx = pd.IndexSlice
dfmi.loc[idx[:, :, ['C1', 'C3']], idx[:, 'foo']]

In [119]:
s = pd.Series(np.random.np.random.randn(5), index=list('abcde'))
s['d'] = s['b']
s

a   -0.231728
b    0.377996
c   -1.463044
d    0.377996
e   -1.508011
dtype: float64

In [128]:
s.rank(method='min', ascending=False)

a    3.0
b    1.0
c    4.0
d    1.0
e    5.0
dtype: float64

In [123]:
s.rank?

In [129]:
df.pct_change?

http://pandas.pydata.org/pandas-docs/stable/computation.html#data-ranking